-- Pruebas PAC adicionales factibles con motor actual (solo plantillas, sin cambios de código)
INSERT OR IGNORE INTO test_templates (code, name, test_type, description, is_standard, config_json) VALUES
('FPT_STD', 'FPT (Pinheiro 880/1122)', 'PPS',
 'Frequency Pattern Test - Variante Pinheiro con tonos grave 880Hz y agudo 1122Hz, 150ms',
 1,
 '{"tones":{"L":{"label":"Grave","frequency":880},"H":{"label":"Agudo","frequency":1122}},"duration_ms":150,"isi_ms":200,"iri_ms":5000,"envelope_ms":10,"pattern_length":3,"practice_sequences":["LHL","HLH","LLH","HHL","LHH","HLL","LHL","HLH","LLH","HHL"],"test_sequences":["LHL","HLH","LLH","HHL","LHH","HLL","LHL","HLH","LLH","HHL","LHH","HLL","LHL","HLH","LLH","HHL","LHH","HLL","LHL","HLH","LLH","HHL","LHH","HLL","LHL","HLH","LLH","HHL","LHH","HLL"],"channel":"binaural","level_db":60}'),
('PPS_LONG', 'PPS extendido (5 tonos)', 'PPS',
 'Patrón de frecuencia de 5 tonos para detección de déficits leves en adultos',
 1,
 '{"tones":{"L":{"label":"Grave","frequency":880},"H":{"label":"Agudo","frequency":1430}},"duration_ms":200,"isi_ms":300,"iri_ms":7000,"envelope_ms":10,"pattern_length":5,"practice_sequences":["LHLHL","HLHLH","LLHHL","HHLLH","LHHLL"],"test_sequences":["LHLHL","HLHLH","LLHHL","HHLLH","LHHLL","HLLHH","LHLLH","HLHLL","LLHLH","HHLHL","LHLHH","HLHLL","LLHHH","HHLLL","LHHLH","HLLHL","LHLHL","HLHLH","LLHHL","HHLLH"],"channel":"binaural","level_db":60}'),
('DPT_LONG', 'DPT extendido (5 tonos)', 'DPS',
 'Patrón de duración de 5 tonos para detección de déficits leves en adultos',
 1,
 '{"frequency":1000,"tones":{"L":{"label":"Largo","duration_ms":500},"C":{"label":"Corto","duration_ms":250}},"isi_ms":300,"iri_ms":7000,"envelope_ms":10,"pattern_length":5,"practice_sequences":["LCLCL","CLCLC","LLCCL","CCLLC","LCCLL"],"test_sequences":["LCLCL","CLCLC","LLCCL","CCLLC","LCCLL","CLLCC","LCLLC","CLCLL","LLCLC","CCLCL","LCLCC","CLCLL","LLCCC","CCLLL","LCCLC","CLLCL","LCLCL","CLCLC","LLCCL","CCLLC"],"channel":"binaural","level_db":60}'),
('DLF_SCREEN', 'DLF screening (Δf=20Hz @ 1kHz)', 'CUSTOM',
 'Discriminación frecuencial - Pares de tonos: ¿iguales o diferentes? Δf=20Hz sobre 1000Hz. Paciente responde "igual" o "distinto", examinador marca.',
 1,
 '{"tones":{"A":{"label":"1000Hz","frequency":1000},"B":{"label":"1020Hz","frequency":1020}},"duration_ms":300,"isi_ms":500,"iri_ms":4000,"envelope_ms":15,"pattern_length":2,"practice_sequences":["AA","AB","BA","BB","AB","AA","BA","BB"],"test_sequences":["AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA"],"channel":"binaural","level_db":60}'),
('DLF_FINE', 'DLF fino (Δf=5Hz @ 1kHz)', 'CUSTOM',
 'Discriminación frecuencial fina - Δf=5Hz, cercano a umbral normal (~3-5Hz). Pares igual/distinto.',
 1,
 '{"tones":{"A":{"label":"1000Hz","frequency":1000},"B":{"label":"1005Hz","frequency":1005}},"duration_ms":400,"isi_ms":500,"iri_ms":4000,"envelope_ms":15,"pattern_length":2,"practice_sequences":["AA","AB","BA","BB","AB","AA","BA","BB"],"test_sequences":["AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA"],"channel":"binaural","level_db":60}'),
('DLD_SCREEN', 'DLD screening (200 vs 250ms)', 'CUSTOM',
 'Discriminación de duración - Pares de tonos mismo Hz, distinta duración. Paciente responde "igual" o "distinto".',
 1,
 '{"frequency":1000,"tones":{"A":{"label":"200ms","duration_ms":200},"B":{"label":"250ms","duration_ms":250}},"isi_ms":500,"iri_ms":4000,"envelope_ms":15,"pattern_length":2,"practice_sequences":["AA","AB","BA","BB","AB","AA","BA","BB"],"test_sequences":["AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA"],"channel":"binaural","level_db":60}'),
('DLD_FINE', 'DLD fino (200 vs 215ms)', 'CUSTOM',
 'Discriminación de duración fina - Δd=15ms, cercano a umbral normal.',
 1,
 '{"frequency":1000,"tones":{"A":{"label":"200ms","duration_ms":200},"B":{"label":"215ms","duration_ms":215}},"isi_ms":500,"iri_ms":4000,"envelope_ms":15,"pattern_length":2,"practice_sequences":["AA","AB","BA","BB","AB","AA","BA","BB"],"test_sequences":["AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA","BA","BB","AA","AB","BA","BB","AB","AA"],"channel":"binaural","level_db":60}'),
('MEM_SEQ_5', 'Memoria secuencial (5 tonos)', 'CUSTOM',
 'Memoria auditiva secuencial - Patrones de 5 tonos. Paciente repite la secuencia. Evalúa retención a corto plazo.',
 1,
 '{"tones":{"L":{"label":"Grave","frequency":880},"H":{"label":"Agudo","frequency":1430}},"duration_ms":250,"isi_ms":400,"iri_ms":6000,"envelope_ms":10,"pattern_length":5,"practice_sequences":["LHLHL","HLHLH","LLHHL"],"test_sequences":["LHLHL","HLHLH","LLHHL","HHLLH","LHHLL","HLLHH","LHLLH","HLHLL","LLHLH","HHLHL","LHLHH","HLHLL","LLHHH","HHLLL","LHHLH","HLLHL"],"channel":"binaural","level_db":60}'),
('MEM_SEQ_6', 'Memoria secuencial (6 tonos)', 'CUSTOM',
 'Memoria auditiva secuencial - Patrones de 6 tonos, carga superior.',
 1,
 '{"tones":{"L":{"label":"Grave","frequency":880},"H":{"label":"Agudo","frequency":1430}},"duration_ms":250,"isi_ms":400,"iri_ms":7000,"envelope_ms":10,"pattern_length":6,"practice_sequences":["LHLHLH","HLHLHL","LLHHLL"],"test_sequences":["LHLHLH","HLHLHL","LLHHLL","HHLLHH","LHHLLH","HLLHHL","LHLLHH","HLHLLH","LLHLHL","HHLHLH","LHLHHL","HLHLLL","LLHHHL","HHLLLH","LHHLHL","HLLHLH"],"channel":"binaural","level_db":60}'),
('MEM_SEQ_7', 'Memoria secuencial (7 tonos)', 'CUSTOM',
 'Memoria auditiva secuencial - Patrones de 7 tonos, límite del span auditivo típico.',
 1,
 '{"tones":{"L":{"label":"Grave","frequency":880},"H":{"label":"Agudo","frequency":1430}},"duration_ms":250,"isi_ms":400,"iri_ms":8000,"envelope_ms":10,"pattern_length":7,"practice_sequences":["LHLHLHL","HLHLHLH","LLHHLLH"],"test_sequences":["LHLHLHL","HLHLHLH","LLHHLLH","HHLLHHL","LHHLLHH","HLLHHLL","LHLLHHL","HLHLLHH","LLHLHLH","HHLHLHL","LHLHHLH","HLHLLLH","LLHHHLL","HHLLLHH","LHHLHLL","HLLHLHH"],"channel":"binaural","level_db":60}');
